# Generated by Django 5.1.3 on 2024-11-26 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('drone_id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude_initial', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude_initial', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude_arrival', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude_arrival', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(default='idle', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('spot_id', models.AutoField(primary_key=True, serialize=False)),
                ('center_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('center_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('top_left_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('top_left_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('top_right_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('top_right_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bottom_left_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bottom_left_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bottom_right_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bottom_right_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('width', models.DecimalField(decimal_places=1, default=2.3, max_digits=4)),
                ('length', models.DecimalField(decimal_places=1, default=5.0, max_digits=4)),
                ('status', models.CharField(default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('parking_spot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Argos_web.parkingspot')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('parking_spot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Argos_web.parkingspot')),
            ],
        ),
    ]
